#pragma once
#include"Push.h"
#include"Add.h"
#include"Pow.h"
#include"Div.h"
#include"Siva.h"
#include"Absolute.h"
#include"Crnobela.h"
#include"DivInvert.h"
#include"Inverzija.h"
#include"Log.h"
#include"Max.h"
#include"Min.h"
#include"Mul.h"
#include"Sub.h"
#include"SubInvert.h"